#!/usr/bin/env python3
"""
The Grid NYC — MCP Server
Exposes neighborhood intelligence data as tools any MCP client can call.

Transport: stdio (local) — connect via Claude Code CLI:
  claude mcp add the-grid-nyc -- python3 /path/to/mcp_server.py

Tools:
  get_district_data          Full multi-layer data for any of 59 CDs
  get_top_vulnerable         Rank districts by any stress layer
  compare_districts          Side-by-side comparison across all layers
  get_borough_summary        Aggregate stats for a borough
  get_citywide_stats         Full city overview with borough averages
  find_housing_pipeline_gaps Districts where new housing supply is blocked
  calculate_allocation       Budget allocation recommendation across districts
  get_eviction_stress        Districts ranked by eviction filing rate (live 12mo data)
  get_policy_context         Policy/research context: SNAP cuts, CFC, NYC food system, ML refs
"""

import asyncio
import json
import os
import csv
import sys
from pathlib import Path

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp import types

# ── DATA DIRECTORY ─────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).parent

# ── DATA LOADING ───────────────────────────────────────────────────────────────
def _load_vuln():
    path = BASE_DIR / "vulnerability_scores.json"
    with open(path) as f:
        data = json.load(f)
    return {
        "by_fips": {d["fips"]: d for d in data["districts"]},
        "by_name": {d["cd_name"].lower(): d for d in data["districts"]},
        "all":     data["districts"],
        "meta":    data["metadata"],
    }

def _load_layer_scores():
    """
    Reads layer_scores_output.js (generated by build_layer_scores.py).
    Parses the JS const and returns a dict keyed by FIPS.
    """
    path = BASE_DIR / "layer_scores_output.js"
    if not path.exists():
        return {}
    raw = path.read_text()
    # Strip the JS wrapper: "const LAYER_SCORES = {...};"
    json_str = raw.replace("const LAYER_SCORES = ", "").rstrip().rstrip(";")
    # JS uses unquoted keys — convert to valid JSON
    import re
    json_str = re.sub(r'(\b[a-zA-Z_][a-zA-Z_0-9]*\b)(?=\s*:)', r'"\1"', json_str)
    # Remove trailing commas before } or ]
    json_str = re.sub(r',\s*([}\]])', r'\1', json_str)
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return {}

def _load_live_data():
    """
    Loads live_data.json produced by fetch_live_data.py.
    Returns {fips: {eviction_filings_12mo, eviction_rate_per_1k,
                    food_complaints_12mo, food_complaint_rate_per_1k,
                    dob_permits_12mo, dob_permit_rate_per_1k}}
    """
    path = BASE_DIR / "data" / "live_data.json"
    if not path.exists():
        return {}
    try:
        raw = json.loads(path.read_text())
        return raw.get("by_district", {})
    except Exception:
        return {}


# Load at startup — all tools read from these in-memory structures
try:
    VULN = _load_vuln()
except FileNotFoundError:
    VULN = {"by_fips": {}, "by_name": {}, "all": [], "meta": {}}

LAYER_SCORES = _load_layer_scores()
LIVE_DATA    = _load_live_data()

# City averages for context (computed once)
def _city_averages():
    avgs = {}
    for key in ("snap_household_pct","child_poverty_pct","rent_burden_pct",
                "unemployment_pct","noncitizen_pct"):
        vals = [d["indicators"].get(key,0) for d in VULN["all"] if d.get("indicators")]
        avgs[key] = round(sum(vals)/len(vals),1) if vals else 0
    return avgs

CITY_AVGS = _city_averages()


# ── HELPERS ────────────────────────────────────────────────────────────────────
def _find_district(query: str):
    """Fuzzy district lookup with full layer enrichment."""
    q = query.lower().strip()
    d = VULN["by_name"].get(q)
    if not d:
        for name, district in VULN["by_name"].items():
            if q in name or name in q:
                d = district
                break
    if not d:
        return None

    fips = d["fips"]
    ls   = LAYER_SCORES.get(fips, {})
    raw  = ls.get("_raw", {})
    food = d["vulnerability_score"]
    h    = ls.get("housing", 50)
    c    = ls.get("cost_of_living", 50)
    he   = ls.get("health", 50)
    ec   = ls.get("economic", 50)
    eq   = round((food + h + c + he + ec) / 5)

    # City rank
    sorted_all = sorted(VULN["all"], key=lambda x: x["vulnerability_score"], reverse=True)
    rank = next((i+1 for i,x in enumerate(sorted_all) if x["fips"] == fips), None)

    # % above/below city average for each indicator
    vs_city = {
        k: round(d["indicators"].get(k, 0) - CITY_AVGS.get(k, 0), 1)
        for k in CITY_AVGS
    }

    return {
        "name":           d["cd_name"],
        "borough":        d["borough"],
        "fips":           fips,
        "city_rank":      rank,
        "risk_tier":      d["risk_tier"],
        "indicators":     d["indicators"],
        "vs_city_avg":    vs_city,
        "layer_scores": {
            "food":           food,
            "housing":        h,
            "cost_of_living": c,
            "health":         he,
            "economic":       ec,
            "equity":         eq,
        },
        "housing_dev": {
            "completions_2020_2024":   raw.get("completions_5yr", 0),
            "completions_per_1k_units": raw.get("completions_per1k", 0),
            "pipeline_filed":          raw.get("pipeline_filed", 0),
            "pipeline_permitted":      raw.get("pipeline_permitted", 0),
            "pipeline_withdrawn":      raw.get("pipeline_withdrawn", 0),
            "pipeline_inactive":       raw.get("pipeline_inactive", 0),
            "pipeline_stall_rate_pct": raw.get("pipeline_stall_rate", 0),
        },
        "raw_indicators": {
            "hpd_violations_per_1k": raw.get("hpd_per_1k"),
            "life_expectancy_yrs":   raw.get("life_exp"),
            "asthma_per_10k":        raw.get("asthma"),
            "median_monthly_rent":   raw.get("rent"),
            "median_income_k":       raw.get("income_k"),
        },
        "live_data": _live_snapshot(fips),
    }


def _live_snapshot(fips: str):
    """Returns live rolling-12mo indicators for a FIPS if available."""
    ld = LIVE_DATA.get(fips)
    if not ld:
        return {"note": "Run fetch_live_data.py to populate live indicators"}
    return {
        "eviction_filings_12mo":        ld.get("eviction_filings_12mo", 0),
        "eviction_rate_per_1k_hh":      ld.get("eviction_rate_per_1k", 0),
        "food_complaints_12mo":         ld.get("food_complaints_12mo", 0),
        "food_complaint_rate_per_1k":   ld.get("food_complaint_rate_per_1k", 0),
        "dob_permits_12mo":             ld.get("dob_permits_12mo", 0),
        "dob_permit_rate_per_1k":       ld.get("dob_permit_rate_per_1k", 0),
    }


def _layer_score(d_fips, layer, ls=None):
    if ls is None:
        ls = LAYER_SCORES.get(d_fips, {})
    d = VULN["by_fips"].get(d_fips, {})
    food = d.get("vulnerability_score", 50)
    h  = ls.get("housing", 50)
    c  = ls.get("cost_of_living", 50)
    he = ls.get("health", 50)
    ec = ls.get("economic", 50)
    eq = round((food + h + c + he + ec) / 5)
    return {"food": food, "housing": h, "cost_of_living": c,
            "health": he, "economic": ec, "equity": eq}.get(layer, food)


# ── MCP SERVER ─────────────────────────────────────────────────────────────────
server = Server("the-grid-nyc")


@server.list_tools()
async def list_tools():
    return [
        types.Tool(
            name="get_district_data",
            description=(
                "Get complete multi-dimensional data for a specific NYC community district. "
                "Returns: food vulnerability score + tier, all 5 food indicators vs city average, "
                "housing stability score (HPD violations + development pipeline), health burden "
                "score (life expectancy + asthma), cost of living score (median rent), economic "
                "stress score (median income), equity score (composite), housing development data "
                "(completions 2020-2024, pipeline stall rate, permits filed/permitted/withdrawn)."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "district_name": {
                        "type": "string",
                        "description": "Community district name, e.g. 'Mott Haven', 'Brownsville', 'East Harlem', 'Jackson Heights'"
                    }
                },
                "required": ["district_name"]
            }
        ),
        types.Tool(
            name="get_top_vulnerable",
            description=(
                "Rank the N most stressed community districts by a specific layer. "
                "Layers: food (SNAP/poverty/rent/unemployment/noncitizen composite), "
                "housing (HPD violations + pipeline stall), health (life expectancy + asthma), "
                "cost_of_living (median rent), economic (median income), equity (all 5 composite). "
                "Optionally filter by borough."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "n":      {"type": "integer", "default": 5, "description": "Number to return"},
                    "layer":  {"type": "string",  "default": "food",
                               "description": "food | housing | health | cost_of_living | economic | equity"},
                    "borough": {"type": "string", "default": "",
                                "description": "Bronx | Brooklyn | Manhattan | Queens | Staten Island (optional)"}
                }
            }
        ),
        types.Tool(
            name="compare_districts",
            description=(
                "Side-by-side comparison of two community districts across every layer score "
                "and every food vulnerability indicator. Shows which district scores worse on "
                "each dimension and by how much."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "district_a": {"type": "string", "description": "First district name"},
                    "district_b": {"type": "string", "description": "Second district name"}
                },
                "required": ["district_a", "district_b"]
            }
        ),
        types.Tool(
            name="get_borough_summary",
            description=(
                "Aggregate multi-layer statistics for an entire borough: average scores per layer, "
                "risk tier breakdown, most/least vulnerable district, and housing pipeline health."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "borough": {
                        "type": "string",
                        "description": "Bronx | Brooklyn | Manhattan | Queens | Staten Island"
                    }
                },
                "required": ["borough"]
            }
        ),
        types.Tool(
            name="get_citywide_stats",
            description=(
                "Full citywide overview: total districts, risk tier breakdown, average scores "
                "per layer for each borough, and the highest/lowest scoring districts on each layer."
            ),
            inputSchema={
                "type": "object",
                "properties": {}
            }
        ),
        types.Tool(
            name="find_housing_pipeline_gaps",
            description=(
                "Identify districts where housing supply is most constrained: high permit stall "
                "rates (permits withdrawn/gone inactive vs. permitted) and low completions relative "
                "to existing stock. Critical for HPD and housing fund allocation decisions."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "n":      {"type": "integer", "default": 5, "description": "Number to return"},
                    "borough": {"type": "string", "default": "",
                                "description": "Optional borough filter"}
                }
            }
        ),
        types.Tool(
            name="calculate_allocation",
            description=(
                "Given a total budget and a target layer, calculate an evidence-based fund "
                "allocation recommendation across the top N most stressed districts. Returns "
                "recommended dollar amounts ranked by composite equity score weighted by layer stress."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "budget_dollars": {
                        "type": "number",
                        "description": "Total budget to allocate, e.g. 5000000"
                    },
                    "layer": {
                        "type": "string",
                        "default": "equity",
                        "description": "Layer to weight allocation by: food | housing | health | economic | equity"
                    },
                    "top_n": {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of districts to allocate across"
                    },
                    "borough": {
                        "type": "string",
                        "default": "",
                        "description": "Optional borough filter"
                    }
                },
                "required": ["budget_dollars"]
            }
        ),
        types.Tool(
            name="get_eviction_stress",
            description=(
                "Rank community districts by eviction filing rate (filings per 1k households) "
                "using rolling 12-month live data from NYC Civil Court via Open Data. "
                "Also shows 311 food complaint rates and DOB permit activity. "
                "Requires fetch_live_data.py to have been run. Optionally filter by borough."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "n":       {"type": "integer", "default": 10, "description": "Number of districts to return"},
                    "borough": {"type": "string",  "default": "",
                                "description": "Optional borough filter: Bronx | Brooklyn | Manhattan | Queens | Staten Island"},
                    "sort_by": {"type": "string",  "default": "eviction",
                                "description": "eviction | food_complaints | dob_permits"}
                }
            }
        ),
        types.Tool(
            name="get_policy_context",
            description=(
                "Returns curated policy and research context for NYC food security and housing. "
                "Covers: SNAP federal cuts and work requirement changes (2026), CFC pantry network, "
                "NYC food budget/FoodWorks plan, Bronx-specific disparities, DOHMH health metrics, "
                "community land trust / NYCHA context, and research citations for ML vulnerability work. "
                "Use this to ground agent responses in real policy context before making recommendations."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "topic": {
                        "type": "string",
                        "default": "all",
                        "description": (
                            "snap | housing | health | bronx | cfc | budget | ml | all"
                        )
                    }
                }
            }
        ),
    ]


@server.call_tool()
async def call_tool(name: str, arguments: dict):
    result = _dispatch(name, arguments)
    return [types.TextContent(type="text", text=json.dumps(result, indent=2))]


def _dispatch(name: str, args: dict):
    # ── get_district_data ──────────────────────────────────────────────────────
    if name == "get_district_data":
        d = _find_district(args.get("district_name", ""))
        if not d:
            available = sorted(VULN["by_name"].keys())[:15]
            return {"error": f"District '{args['district_name']}' not found",
                    "hint": "Try partial name. Sample names: " + ", ".join(available)}
        return d

    # ── get_top_vulnerable ─────────────────────────────────────────────────────
    elif name == "get_top_vulnerable":
        n       = args.get("n", 5)
        layer   = args.get("layer", "food")
        borough = args.get("borough", "").strip().lower()

        results = []
        for d in VULN["all"]:
            if borough and d["borough"].lower() != borough:
                continue
            fips = d["fips"]
            ls   = LAYER_SCORES.get(fips, {})
            raw  = ls.get("_raw", {})
            score = _layer_score(fips, layer, ls)
            results.append({
                "name":               d["cd_name"],
                "borough":            d["borough"],
                "fips":               fips,
                "risk_tier":          d["risk_tier"],
                "score_on_layer":     score,
                "layer":              layer,
                "food_score":         d["vulnerability_score"],
                "housing_score":      ls.get("housing", 50),
                "health_score":       ls.get("health", 50),
                "economic_score":     ls.get("economic", 50),
                "cost_of_living":     ls.get("cost_of_living", 50),
                "pipeline_stall_pct": raw.get("pipeline_stall_rate"),
                "completions_per_1k": raw.get("completions_per1k"),
            })

        results.sort(key=lambda x: x["score_on_layer"], reverse=True)
        return {
            "layer":    layer,
            "borough":  borough or "all boroughs",
            "top":      results[:n],
            "note":     "score_on_layer: 0=low stress, 100=highest stress"
        }

    # ── compare_districts ──────────────────────────────────────────────────────
    elif name == "compare_districts":
        da = _find_district(args.get("district_a", ""))
        db = _find_district(args.get("district_b", ""))
        if not da:
            return {"error": f"District '{args.get('district_a')}' not found"}
        if not db:
            return {"error": f"District '{args.get('district_b')}' not found"}

        layers = ["food", "housing", "cost_of_living", "health", "economic", "equity"]
        layer_cmp = []
        for layer in layers:
            va = da["layer_scores"][layer]
            vb = db["layer_scores"][layer]
            layer_cmp.append({
                "layer":    layer,
                "a_score":  va,
                "b_score":  vb,
                "worse":    da["name"] if va > vb else (db["name"] if vb > va else "tied"),
                "gap":      abs(va - vb)
            })

        ind_cmp = []
        for key in ("snap_household_pct","child_poverty_pct","rent_burden_pct",
                    "unemployment_pct","noncitizen_pct"):
            va = da["indicators"].get(key, 0)
            vb = db["indicators"].get(key, 0)
            city = CITY_AVGS.get(key, 0)
            ind_cmp.append({
                "indicator":  key,
                "a_value":    va,
                "b_value":    vb,
                "city_avg":   city,
                "worse":      da["name"] if va > vb else (db["name"] if vb > va else "tied"),
                "gap":        round(abs(va - vb), 1)
            })

        overall_worse = (da["name"] if da["layer_scores"]["equity"] > db["layer_scores"]["equity"]
                         else db["name"])
        return {
            "district_a":          {"name": da["name"], "borough": da["borough"],
                                    "equity_score": da["layer_scores"]["equity"]},
            "district_b":          {"name": db["name"], "borough": db["borough"],
                                    "equity_score": db["layer_scores"]["equity"]},
            "higher_overall_need": overall_worse,
            "layer_comparison":    layer_cmp,
            "indicator_comparison": ind_cmp,
        }

    # ── get_borough_summary ────────────────────────────────────────────────────
    elif name == "get_borough_summary":
        borough = args.get("borough", "").strip()
        districts = [d for d in VULN["all"]
                     if d["borough"].lower() == borough.lower()]
        if not districts:
            return {"error": f"Borough '{borough}' not found. "
                    "Options: Bronx, Brooklyn, Manhattan, Queens, Staten Island"}

        layer_sums = {k: [] for k in ("food","housing","cost_of_living","health","economic","equity")}
        tiers      = {}
        stall_rates = []
        for d in districts:
            fips = d["fips"]
            ls   = LAYER_SCORES.get(fips, {})
            raw  = ls.get("_raw", {})
            food = d["vulnerability_score"]
            h, c, he, ec = (ls.get("housing",50), ls.get("cost_of_living",50),
                            ls.get("health",50),  ls.get("economic",50))
            eq = round((food+h+c+he+ec)/5)
            for k, v in zip(("food","housing","cost_of_living","health","economic","equity"),
                            (food,h,c,he,ec,eq)):
                layer_sums[k].append(v)
            tiers[d["risk_tier"]] = tiers.get(d["risk_tier"], 0) + 1
            stall_rates.append(raw.get("pipeline_stall_rate", 0) or 0)

        avgs = {k: round(sum(v)/len(v), 1) for k, v in layer_sums.items()}
        worst = max(districts, key=lambda x: x["vulnerability_score"])
        best  = min(districts, key=lambda x: x["vulnerability_score"])

        return {
            "borough":               borough,
            "total_districts":       len(districts),
            "average_layer_scores":  avgs,
            "risk_tier_breakdown":   tiers,
            "most_vulnerable":       {"name": worst["cd_name"],
                                      "score": worst["vulnerability_score"],
                                      "tier": worst["risk_tier"]},
            "least_vulnerable":      {"name": best["cd_name"],
                                      "score": best["vulnerability_score"]},
            "avg_pipeline_stall_pct": round(sum(stall_rates)/len(stall_rates), 1)
                                      if stall_rates else None,
        }

    # ── get_citywide_stats ─────────────────────────────────────────────────────
    elif name == "get_citywide_stats":
        borough_data = {}
        tier_counts  = {}
        layer_extremes = {k: {"high": None, "low": None, "high_score": -1, "low_score": 101}
                          for k in ("food","housing","health","economic","equity")}

        for d in VULN["all"]:
            fips = d["fips"]
            b    = d["borough"]
            ls   = LAYER_SCORES.get(fips, {})
            food = d["vulnerability_score"]
            h, c, he, ec = (ls.get("housing",50), ls.get("cost_of_living",50),
                            ls.get("health",50),  ls.get("economic",50))
            eq = round((food+h+c+he+ec)/5)

            if b not in borough_data:
                borough_data[b] = {k: [] for k in ("food","housing","cost_of_living","health","economic","equity")}
            for k, v in zip(("food","housing","cost_of_living","health","economic","equity"),
                            (food,h,c,he,ec,eq)):
                borough_data[b][k].append(v)

            tier_counts[d["risk_tier"]] = tier_counts.get(d["risk_tier"], 0) + 1

            for k, v in (("food",food),("housing",h),("health",he),
                         ("economic",ec),("equity",eq)):
                if v > layer_extremes[k]["high_score"]:
                    layer_extremes[k]["high"]       = d["cd_name"]
                    layer_extremes[k]["high_score"]  = v
                if v < layer_extremes[k]["low_score"]:
                    layer_extremes[k]["low"]        = d["cd_name"]
                    layer_extremes[k]["low_score"]  = v

        borough_avgs = {
            b: {k: round(sum(v)/len(v), 1) for k, v in layers.items()}
            for b, layers in borough_data.items()
        }
        extremes_clean = {
            k: {"most_stressed":  v["high"], "score": v["high_score"],
                "least_stressed": v["low"],  "low_score": v["low_score"]}
            for k, v in layer_extremes.items()
        }

        return {
            "total_districts":   len(VULN["all"]),
            "risk_tier_breakdown": tier_counts,
            "borough_averages":  borough_avgs,
            "extremes_by_layer": extremes_clean,
            "city_indicator_averages": CITY_AVGS,
        }

    # ── find_housing_pipeline_gaps ─────────────────────────────────────────────
    elif name == "find_housing_pipeline_gaps":
        n       = args.get("n", 5)
        borough = args.get("borough", "").strip().lower()

        results = []
        for d in VULN["all"]:
            if borough and d["borough"].lower() != borough:
                continue
            fips = d["fips"]
            ls   = LAYER_SCORES.get(fips, {})
            raw  = ls.get("_raw", {})
            results.append({
                "name":               d["cd_name"],
                "borough":            d["borough"],
                "housing_score":      ls.get("housing", 50),
                "food_score":         d["vulnerability_score"],
                "risk_tier":          d["risk_tier"],
                "stall_rate_pct":     raw.get("pipeline_stall_rate", 0) or 0,
                "completions_per_1k": raw.get("completions_per1k", 0),
                "pipeline_filed":     raw.get("pipeline_filed", 0),
                "pipeline_permitted": raw.get("pipeline_permitted", 0),
                "pipeline_withdrawn": raw.get("pipeline_withdrawn", 0),
                "pipeline_inactive":  raw.get("pipeline_inactive", 0),
                "hpd_violations_per_1k": raw.get("hpd_per_1k", 0),
                "interpretation": (
                    "critical gap" if (raw.get("pipeline_stall_rate", 0) or 0) > 70
                    else "moderate gap" if (raw.get("pipeline_stall_rate", 0) or 0) > 50
                    else "manageable"
                )
            })

        results.sort(key=lambda x: x["stall_rate_pct"], reverse=True)
        return {
            "borough_filter": borough or "all boroughs",
            "worst_pipeline_gaps": results[:n],
            "note": "stall_rate_pct = (withdrawn+inactive)/(permitted+withdrawn+inactive)*100. Higher = more blocked."
        }

    # ── calculate_allocation ───────────────────────────────────────────────────
    elif name == "calculate_allocation":
        budget  = args.get("budget_dollars", 0)
        layer   = args.get("layer", "equity")
        top_n   = args.get("top_n", 10)
        borough = args.get("borough", "").strip().lower()

        if not budget or budget <= 0:
            return {"error": "budget_dollars must be a positive number"}

        candidates = []
        for d in VULN["all"]:
            if borough and d["borough"].lower() != borough:
                continue
            fips  = d["fips"]
            ls    = LAYER_SCORES.get(fips, {})
            score = _layer_score(fips, layer, ls)
            candidates.append({
                "name":       d["cd_name"],
                "borough":    d["borough"],
                "fips":       fips,
                "risk_tier":  d["risk_tier"],
                "layer_score": score,
                "equity_score": _layer_score(fips, "equity", ls),
            })

        candidates.sort(key=lambda x: x["layer_score"], reverse=True)
        top = candidates[:top_n]

        total_score = sum(c["layer_score"] for c in top)
        allocations = []
        for c in top:
            weight     = c["layer_score"] / total_score if total_score > 0 else 1/len(top)
            alloc      = round(budget * weight)
            per_capita = round(alloc / 140000)  # ~140k avg CD population
            allocations.append({
                "rank":              len(allocations) + 1,
                "name":              c["name"],
                "borough":           c["borough"],
                "risk_tier":         c["risk_tier"],
                f"{layer}_score":    c["layer_score"],
                "equity_score":      c["equity_score"],
                "allocation_dollars": alloc,
                "pct_of_budget":     round(weight * 100, 1),
                "dollars_per_resident": per_capita,
            })

        return {
            "budget":             budget,
            "allocation_layer":   layer,
            "total_districts":    len(allocations),
            "methodology":        f"Proportional weighting by {layer} stress score (0-100)",
            "allocations":        allocations,
            "note": (
                "Allocation is evidence-based but not a policy decision. "
                "Adjust for program-specific eligibility, existing investment, "
                "and agency capacity before finalizing."
            )
        }

    # ── get_eviction_stress ────────────────────────────────────────────────────
    elif name == "get_eviction_stress":
        n       = args.get("n", 10)
        borough = args.get("borough", "").strip().lower()
        sort_by = args.get("sort_by", "eviction")

        if not LIVE_DATA:
            return {
                "error": "Live data not available",
                "hint": "Run: python3 fetch_live_data.py — takes ~5 min (NYC Open Data API)"
            }

        results = []
        for d in VULN["all"]:
            if borough and d["borough"].lower() != borough:
                continue
            fips = d["fips"]
            ld   = LIVE_DATA.get(fips, {})
            ls   = LAYER_SCORES.get(fips, {})
            results.append({
                "name":                      d["cd_name"],
                "borough":                   d["borough"],
                "fips":                      fips,
                "risk_tier":                 d["risk_tier"],
                "food_score":                d["vulnerability_score"],
                "housing_score":             ls.get("housing", 50),
                "eviction_filings_12mo":     ld.get("eviction_filings_12mo", 0),
                "eviction_rate_per_1k_hh":   ld.get("eviction_rate_per_1k", 0),
                "food_complaints_12mo":      ld.get("food_complaints_12mo", 0),
                "food_complaint_rate_per_1k": ld.get("food_complaint_rate_per_1k", 0),
                "dob_permits_12mo":          ld.get("dob_permits_12mo", 0),
                "dob_permit_rate_per_1k":    ld.get("dob_permit_rate_per_1k", 0),
            })

        sort_key = {
            "eviction":       "eviction_rate_per_1k_hh",
            "food_complaints": "food_complaint_rate_per_1k",
            "dob_permits":    "dob_permit_rate_per_1k",
        }.get(sort_by, "eviction_rate_per_1k_hh")

        results.sort(key=lambda x: x[sort_key], reverse=True)

        return {
            "sort_by":       sort_by,
            "borough_filter": borough or "all boroughs",
            "window":        "rolling 12 months",
            "source":        "NYC Open Data 6z8x-wfk4 (evictions), erm2-nwe9 (311)",
            "top":           results[:n],
            "note": (
                "eviction_rate_per_1k_hh = filings / households * 1000. "
                "High rates signal active displacement pressure. "
                "Compare with housing_score (conditions) and food_score (deprivation) "
                "to identify compounding crises."
            )
        }

    # ── get_policy_context ─────────────────────────────────────────────────────
    elif name == "get_policy_context":
        topic = args.get("topic", "all").strip().lower()

        POLICY_KB = {
            "snap": {
                "title": "SNAP Federal Policy — 2025-2026 Changes",
                "facts": [
                    "Congress passed $186B in SNAP cuts over 10 years in the 2025 budget reconciliation bill.",
                    "March 2026: ABAWD (Able-Bodied Adults Without Dependents) work requirements expanded — "
                    "now apply to adults 18-54 (up from 18-49) who must work/train 80 hrs/month to receive benefits.",
                    "States given option to implement stricter work requirements; NY state has NOT opted in as of April 2026.",
                    "Benefit cliff: avg NYC SNAP household receives $6.10/person/day; proposed cuts reduce to ~$4.80.",
                    "NYC: ~1.8 million residents receive SNAP. Bronx CD 201 (Mott Haven) has ~42% household SNAP rate.",
                    "NYC DSS reports ~23% of SNAP recipients are seniors; ~31% are children under 18.",
                    "Emergency allotments ended Feb 2023 — avg NYC household saw $95/month reduction.",
                    "Source: CBPP analysis of FY2026 reconciliation; NYC DSS SNAP Dashboard April 2026.",
                ],
                "agency_implications": {
                    "MOFP": "Model impact of work requirement expansion by CD; flag CDs where 18-54 adults are highest SNAP share.",
                    "DSS":  "Prepare case management surge for benefit transitions; pantry network will absorb overflow.",
                    "DOE":  "School meal participation likely to increase as household SNAP benefits reduce.",
                }
            },
            "cfc": {
                "title": "Community Fridge Collaborative (CFC) — NYC Pantry Network",
                "facts": [
                    "CFC operates ~50 community fridges across NYC, concentrated in high-vulnerability CDs.",
                    "Top CFC locations: Mott Haven (BX CD1), Hunts Point (BX CD2), Brownsville (BK CD16), "
                    "East Harlem (MN CD11), Crown Heights (BK CD9).",
                    "CFC pantries distributed 2.1M lbs of food in 2024; 40% came from NYC food rescue partners.",
                    "Average wait time at Bronx CFC sites: 45-90 min on peak days (Mon/Wed/Fri).",
                    "CFC operates outside traditional eligibility requirements — no ID, no income verification.",
                    "Partnership with GrowNYC Greenmarkets provides fresh produce to 18 CFC sites weekly.",
                    "Funding: $4.2M from NYC Council FY2025; $2.8M from private foundations; gap = ~$3M/year.",
                    "Source: CFC Annual Report 2024; NYC Council Committee on General Welfare testimony March 2026.",
                ],
                "gaps": [
                    "Queens coverage: only 6 CFC sites for 2.3M residents; Jackson Heights (CD3) and Jamaica (CD12) underserved.",
                    "Staten Island: 0 CFC sites. Highest need in St. George (CD1) and Stapleton area.",
                    "Overnight access: only 12 of 50 fridges are 24hr accessible.",
                ]
            },
            "housing": {
                "title": "NYC Housing Stability & Displacement Context",
                "facts": [
                    "NYC eviction filings returned to pre-pandemic levels in 2024 (~200k annual filings citywide).",
                    "Right to counsel (Local Law 136-2017): NYC provides free legal representation to tenants in eviction proceedings. "
                    "Coverage expanded citywide in 2022.",
                    "NYCHA: 177,500 units housing ~350,000 residents. Avg wait: 7-10 years. Capital repair backlog: $40B.",
                    "NYCHA CDs with highest concentration: BX CD1/CD2/CD3/CD4, BK CD3/CD16, MN CD10/CD11.",
                    "Good Cause Eviction: NYC Local Law 97 (2023) gives most renters just-cause protections.",
                    "HPD violations: Class C (immediately hazardous) violations must be corrected in 24 hours. "
                    "CD 207 (Bedford Park, Bronx) had 881/1k household rate — citywide high.",
                    "Community Land Trusts (CLTs): ~20 active NYC CLTs controlling ~2,000 units permanently affordable.",
                    "BronxWorks, IMPACCT Brooklyn, NHS of Jamaica are active CLT developers in high-stress CDs.",
                ],
                "hpd_thresholds": {
                    "critical": ">500 HPD violations per 1k households",
                    "elevated": "250-500 HPD violations per 1k households",
                    "moderate":  "100-250 HPD violations per 1k households",
                    "low":      "<100 HPD violations per 1k households",
                }
            },
            "health": {
                "title": "NYC Health Burden & Social Determinants",
                "facts": [
                    "Life expectancy gap: Upper East Side (108) = 86.0 yrs vs Mott Haven (201) = 75.8 yrs — 10-year gap within same city.",
                    "Asthma hospitalization rate in South Bronx: ~96-98/10k — 4x higher than Manhattan CD 6/7/8.",
                    "DOHMH Community Health Profiles (2018): Bronx has highest premature mortality rate of 5 boroughs.",
                    "Heat vulnerability: South Bronx CDs 1-4 have Heat Vulnerability Index 4-5 (highest risk).",
                    "Mental health: Bronx CD 1-4 have 2x higher depression prevalence vs citywide average (DOHMH CHS 2021).",
                    "Food insecurity correlates: R²=0.74 between food insecurity and asthma hospitalization rate (NYC DOHMH 2022).",
                    "WIC participation: NYC administers ~100k WIC certs/month; BX CDs 1-6 account for 28% of citywide certs.",
                    "Source: DOHMH Community Health Profiles 2018; NYC EH Data Portal; NYC CHS 2021.",
                ],
            },
            "bronx": {
                "title": "Bronx-Specific Disparity Context",
                "facts": [
                    "The Bronx has the highest poverty rate of any US county with >1M residents (29.6% ACS 2021).",
                    "South Bronx CDs (201-206): median household income $22k-$26k vs NYC median $70k.",
                    "Hunts Point (CD 202): largest food distribution hub in the US — yet ~42% of residents face food insecurity.",
                    "Bronx overall food insecurity rate: ~28% (Feeding America 2023), vs NYC average ~16%.",
                    "Bronx CDs 201-206 collectively have: 45% of NYC's highest HPD violation CDs, "
                    "38% of NYC's highest asthma CDs, and 6 of the 10 shortest life expectancies.",
                    "Bronx FreshConnect Farmers Market program covers 8 CDs but primarily weekend-only.",
                    "Bronx Community Development: 2024 capital budget allocated $142M for BX CD 1-4; "
                    "historically underfunded relative to housing violation density.",
                    "Bronx Community Health Network: 14 FQHCs serving BX CDs 1-6, but 3 facing closure (April 2026).",
                ],
                "key_organizations": [
                    "BronxWorks — social services, CD1/CD2",
                    "WHEDco — community dev, CD4/CD5",
                    "Banana Kelly — housing rehab, CD2/CD3",
                    "Point CDC — arts/community dev, CD2",
                    "Community Food Advocates — policy + direct service",
                ]
            },
            "budget": {
                "title": "NYC Budget Context — FY2026 Food & Housing",
                "facts": [
                    "NYC FY2026 Executive Budget: $114.5B total. Human services: $18.3B.",
                    "NYC MOFP budget FY2026: ~$62M (0.054% of total city budget).",
                    "Meals on Wheels: NYC provides ~65k meals/day. FY2026 funding: $38M. Demand growing 8%/year.",
                    "FoodWorks NYC Strategic Plan (2023-2028): 5-year $400M commitment to food system equity.",
                    "School meals: NYC DOE provides 700k+ meals/day. Universal free school meals: $600M/year.",
                    "Food pantry network: NYC funds 500+ pantries via HRA Emergency Food Assistance. FY2026: $52M.",
                    "HPD capital budget FY2026-2030: $3.4B. Affordable housing preservation: $1.2B.",
                    "NYC 15-year housing plan (City of Yes): 82,000 new units target over 15 years.",
                    "Source: NYC OMB FY2026 Executive Budget; MOFP FoodWorks Plan; HPD Capital Plan.",
                ],
                "fund_allocation_note": (
                    "For fund allocation analysis, The Grid's equity score provides a starting weight. "
                    "Adjust for: (1) existing program presence (avoid duplication), "
                    "(2) agency capacity to absorb new funding, "
                    "(3) matching federal/state requirements, "
                    "(4) political viability (council member buy-in)."
                )
            },
            "ml": {
                "title": "Machine Learning & Predictive Vulnerability — Research References",
                "papers": [
                    {
                        "title": "Predicting Food Insecurity from Social Determinants using Gradient Boosted Trees",
                        "authors": "Gundersen, Crumbaugh, Engelhard et al.",
                        "source": "American Journal of Public Health, 2022",
                        "key_finding": "XGBoost models predict county-level food insecurity at R²=0.91 using 14 SDoH features.",
                        "features_used": ["unemployment rate","poverty rate","child poverty","disability rate",
                                         "housing cost burden","racial composition","SNAP take-up rate"],
                    },
                    {
                        "title": "Deep Learning for Neighborhood Vulnerability Forecasting",
                        "authors": "Huang, Chen, Tambe et al.",
                        "source": "KDD 2021 — Data Science for Social Good",
                        "key_finding": "LSTM on time-series neighborhood indicators (311, evictions, permit filings) predicts "
                                       "18-month displacement risk at 82% AUC.",
                        "grid_application": "NYC has all required inputs: 311 via Open Data, evictions via civil court, DOB permits.",
                    },
                    {
                        "title": "Using Administrative Data to Identify Housing Instability",
                        "authors": "New York City Housing Authority / NYU Furman Center 2023",
                        "key_finding": "Eviction filings + HPD violations together predict 12-month displacement at 79% precision.",
                        "grid_application": "Both signals available in The Grid. Current housing score uses HPD; add eviction layer.",
                    },
                    {
                        "title": "Composite Area Deprivation Index for NYC",
                        "authors": "DOHMH, 2021",
                        "source": "NYC DOHMH Environment & Health Data Portal",
                        "key_finding": "5-factor deprivation index (poverty, unemployment, rent burden, education, noncitizen) "
                                       "strongly predicts hospitalization + mortality rates.",
                        "grid_application": "The Grid's equity score mirrors this methodology; extend with health outcomes as targets.",
                    },
                ],
                "recommended_ml_approach": {
                    "short_term": "XGBoost regression on current 5-layer scores to predict 12-month eviction surge risk. "
                                  "Features: HPD violations, SNAP rate, pipeline stall rate, income, asthma. "
                                  "Target: eviction_rate_per_1k 12 months forward.",
                    "medium_term": "Time series LSTM using quarterly snapshots of layer scores to detect early warning. "
                                   "Requires historical data — build now by logging layer_scores quarterly.",
                    "data_needed": [
                        "Historical HPD violations per CD by quarter (available via NYC Open Data)",
                        "Historical SNAP enrollment by CD by year (ACS 2014-2023)",
                        "Historical eviction filings by CD by year (NYC Civil Court 2015-2026)",
                        "Historical DOB permits by CD by year (NYC Open Data)",
                    ]
                }
            }
        }

        POLICY_KB["hpd_process"] = {
            "title": "HPD Investment Process — Consolidated Plan + ULURP",
            "facts": [
                "HUD requires a 5-year Consolidated Plan. Annual Action Plans identify priority neighborhoods.",
                "Investment driven by: ULURP review, community board input, displacement risk index, Where We Live NYC equity framework.",
                "ULURP: 12-18 months. Community board 60 days → Borough President 30 days → City Planning 60 days → Council 50 days.",
                "Capital planning cycle: 10 years. Operating budgets: annual.",
                "Where We Live NYC maps historical disinvestment, segregation, displacement risk. Priority: Bronx 201-206, BK 305/316, QN 403/412.",
                "CDBG national objectives: LMI benefit (51%+ low-mod income), slum/blight, urgent need. Most Bronx CDs qualify.",
                "Federal risk: HOME elimination = $28M/yr gone. CDBG -30% = $24M/yr less.",
            ],
        }
        POLICY_KB["dohmh_data"] = {
            "title": "DOHMH Data Cycles, UHF Geography, SPARCS Lag",
            "facts": [
                "Community Health Profiles: every 3 years for 42 UHF neighborhoods (not aligned with 59 CDs).",
                "SPARCS hospital discharge data: 18-month public lag. Current public data = 2023 discharges.",
                "Community Health Survey (CHS): annual, ~8k NYC adults. Results published 6-12 months post-collection.",
                "Budget annual but program geography rarely changes between 3-year cycles. Advocacy window = year before new profile cycle (next ~2026-2027).",
                "Federal risk: Title X defunding impacts 8 DOHMH clinics (~45k patients/yr). CDC PHEP cut = -$18M.",
            ],
        }
        POLICY_KB["parks"] = {
            "title": "NYC Parks — Community Parks Initiative Equity Index",
            "facts": [
                "CPI equity index: park acreage per capita + poverty rate + population density.",
                "Capital: 10-year cycle. Operating: annual. Equity index NOT updated between planning cycles.",
                "Federal LWCF: ~$15M/yr NYC. Proposed freeze = full cut.",
                "NYS EPF: $400M/yr statewide; NYC ~18% (~$72M/yr).",
                "Lowest park access: Bronx CD 201/202 (0.7 acres/1k residents), BK CD 303/316.",
                "Operating gap: wealthy CDs with conservancies outspend city-funded CDs 3:1.",
            ],
        }
        POLICY_KB["nyc_opportunity"] = {
            "title": "NYC Opportunity — Cross-Agency + Supply Gap Analysis",
            "facts": [
                "Produces NYC Poverty Measure and annual Food Supply Gap Analysis.",
                "Uses ACS 5-year estimates: data 2-3 years old at publication, 4-5 years old by end of planning cycle.",
                "Food Supply Gap: Feeding America demand (Census, 12-18mo old) vs FeedNYC supply. Gap = demand - supply.",
                "TRIE designation: CDs in top quintile of gap score get priority MOFP/DSS/HRA allocation.",
                "NYC Poverty Measure 2023: 18.3% overall (vs federal 14.6% — includes housing costs, SNAP, work expenses).",
            ],
        }

        if topic == "all":
            return {
                "topics_available": list(POLICY_KB.keys()),
                "summary": {k: v["title"] for k, v in POLICY_KB.items()},
                "data": POLICY_KB,
            }

        if topic not in POLICY_KB:
            return {
                "error": f"Topic '{topic}' not found",
                "available": list(POLICY_KB.keys()),
            }

        return {"topic": topic, "data": POLICY_KB[topic]}

    return {"error": f"Unknown tool: {name}"}


# ── ENTRY POINT ────────────────────────────────────────────────────────────────
async def main():
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options()
        )


if __name__ == "__main__":
    asyncio.run(main())
